2021-02-15 12:46:34,147 (7449/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-15 12:46:34,147 (7449/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-15 14:08:51,507 (60681/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-15 14:08:51,507 (60681/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-15 14:09:10,720 (60681/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2021-02-15 14:09:10,721 (60681/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2021-02-15 14:09:15,637 (60681/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-02-15 14:09:15,637 (60681/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-02-15 14:09:17,743 (60681/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-02-15 14:09:17,743 (60681/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-02-15 14:35:01,190 (76590/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-15 14:35:01,191 (76590/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-16 21:37:54,706 (47606/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-16 21:37:54,706 (47606/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-16 21:39:02,805 (47606/MainThread) pgcli.pgexecute ERROR - sql: 'lc compeya', error: SyntaxError('syntax error at or near "lc"\nLINE 1: lc compeya\n        ^\n')
2021-02-16 21:39:02,806 (47606/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "lc"\nLINE 1: lc compeya\n        ^\n\n'
2021-02-25 14:02:56,593 (90281/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-25 14:02:56,593 (90281/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-25 14:32:21,925 (9356/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-25 14:32:21,925 (9356/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-25 23:49:02,225 (57696/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-25 23:49:02,226 (57696/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-25 23:52:31,652 (59913/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-25 23:52:31,652 (59913/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-26 09:19:31,713 (61332/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-26 09:19:31,713 (61332/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-26 09:51:01,180 (81231/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-26 09:51:01,180 (81231/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-04 14:36:02,264 (48385/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-04 14:36:02,265 (48385/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 16:31:26,634 (19120/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 16:31:26,634 (19120/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 16:32:02,005 (19120/MainThread) pgcli.pgexecute ERROR - sql: 'select * from tenki_user', error: UndefinedTable('relation "tenki_user" does not exist\nLINE 1: select * from tenki_user\n                      ^\n')
2021-03-12 16:32:02,007 (19120/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "tenki_user" does not exist\nLINE 1: select * from tenki_user\n                      ^\n\n'
2021-03-18 17:35:32,305 (46363/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-18 17:35:32,305 (46363/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-18 17:35:44,607 (46363/MainThread) pgcli.pgexecute ERROR - sql: 'select * from ussers', error: UndefinedTable('relation "ussers" does not exist\nLINE 1: select * from ussers\n                      ^\n')
2021-03-18 17:35:44,608 (46363/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "ussers" does not exist\nLINE 1: select * from ussers\n                      ^\n\n'
2021-03-18 17:38:57,841 (48610/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-18 17:38:57,841 (48610/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-18 17:39:05,324 (48610/MainThread) pgcli.pgexecute ERROR - sql: 'sele', error: SyntaxError('syntax error at or near "sele"\nLINE 1: sele\n        ^\n')
2021-03-18 17:39:05,325 (48610/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "sele"\nLINE 1: sele\n        ^\n\n'
2021-03-18 19:37:47,069 (26194/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-18 19:37:47,069 (26194/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-18 19:38:54,021 (26194/MainThread) pgcli.pgexecute ERROR - sql: 'select & from tenki_user_areas', error: SyntaxError('syntax error at or near "from"\nLINE 1: select & from tenki_user_areas\n                 ^\n')
2021-03-18 19:38:54,022 (26194/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "from"\nLINE 1: select & from tenki_user_areas\n                 ^\n\n'
2021-03-18 19:45:00,342 (30809/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-18 19:45:00,342 (30809/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-18 19:52:45,141 (36026/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-18 19:52:45,141 (36026/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 04:58:30,265 (87129/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 04:58:30,265 (87129/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 05:09:40,837 (95142/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 05:09:40,837 (95142/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 06:05:59,550 (35335/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 06:05:59,550 (35335/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 08:33:09,808 (35335/MainThread) pgcli.pgexecute ERROR - sql: 'show columns from properties', error: SyntaxError('syntax error at or near "from"\nLINE 1: show columns from properties\n                     ^\n')
2021-03-20 08:33:09,812 (35335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "from"\nLINE 1: show columns from properties\n                     ^\n\n'
2021-03-20 08:33:16,084 (35335/MainThread) pgcli.pgexecute ERROR - sql: 'show column from properties', error: SyntaxError('syntax error at or near "column"\nLINE 1: show column from properties\n             ^\n')
2021-03-20 08:33:16,084 (35335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "column"\nLINE 1: show column from properties\n             ^\n\n'
2021-03-20 08:33:44,297 (35335/MainThread) pgcli.pgexecute ERROR - sql: '/d', error: SyntaxError('syntax error at or near "/"\nLINE 1: /d\n        ^\n')
2021-03-20 08:33:44,297 (35335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /d\n        ^\n\n'
2021-03-20 17:15:08,297 (87398/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 17:15:08,297 (87398/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 17:42:19,113 (7841/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 17:42:19,114 (7841/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 17:42:49,242 (7841/MainThread) pgcli.pgexecute ERROR - sql: 'exir', error: SyntaxError('syntax error at or near "exir"\nLINE 1: exir\n        ^\n')
2021-03-20 17:42:49,244 (7841/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "exir"\nLINE 1: exir\n        ^\n\n'
2021-03-20 17:55:10,391 (16584/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 17:55:10,392 (16584/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 17:55:12,137 (16584/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-20 17:55:13,958 (16632/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 17:55:13,958 (16632/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 17:59:56,727 (19838/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 17:59:56,727 (19838/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 17:59:58,609 (19838/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-20 18:00:00,462 (19868/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 18:00:00,463 (19868/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-20 22:12:46,410 (92363/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-20 22:12:46,411 (92363/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-21 16:08:18,193 (12117/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-21 16:08:18,193 (12117/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-21 16:08:21,321 (12117/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-21 16:08:23,595 (12198/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-21 16:08:23,595 (12198/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-21 16:11:36,232 (15826/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-21 16:11:36,232 (15826/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-21 16:51:38,951 (68380/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-21 16:51:38,951 (68380/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-21 16:51:42,205 (68380/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "ikasa" does not exist\n\n'
2021-03-21 16:51:49,358 (68608/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-21 16:51:49,358 (68608/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-22 22:18:56,388 (46565/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-22 22:18:56,388 (46565/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-22 23:02:34,325 (1497/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-22 23:02:34,325 (1497/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-22 23:02:36,523 (1497/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-22 23:02:39,526 (1590/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-22 23:02:39,526 (1590/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-22 23:03:30,554 (2735/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-22 23:03:30,554 (2735/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-22 23:08:14,030 (9316/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-22 23:08:14,030 (9316/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-23 01:15:18,887 (58907/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-23 01:15:18,888 (58907/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-23 01:15:20,388 (58907/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-23 01:15:22,863 (59001/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-23 01:15:22,869 (59001/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-23 01:15:27,568 (59001/MainThread) pgcli.pgexecute ERROR - sql: 'select * from properties', error: UndefinedTable('relation "properties" does not exist\nLINE 1: select * from properties\n                      ^\n')
2021-03-23 01:15:27,569 (59001/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "properties" does not exist\nLINE 1: select * from properties\n                      ^\n\n'
2021-03-23 01:16:01,038 (59816/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-23 01:16:01,038 (59816/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-24 04:16:19,957 (95459/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-24 04:16:19,957 (95459/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-24 04:16:20,418 (95459/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-03-24 04:27:39,563 (10003/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-24 04:27:39,567 (10003/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-24 04:28:06,060 (10003/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2021-03-24 04:28:06,061 (10003/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2021-03-26 22:13:41,084 (2176/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-26 22:13:41,085 (2176/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-26 22:13:41,097 (2176/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 6543?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 6543?\n\n'
2021-03-26 22:14:04,613 (2664/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-26 22:14:04,613 (2664/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-26 22:14:04,625 (2664/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 6543?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 6543?\n\n'
2021-03-26 22:14:10,441 (2789/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-26 22:14:10,442 (2789/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:34:08,209 (64626/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:34:08,209 (64626/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:34:09,659 (64626/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-03-27 18:34:17,405 (64840/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:34:17,405 (64840/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:34:19,210 (64840/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-03-27 18:34:22,312 (64931/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:34:22,312 (64931/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:34:24,668 (64931/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postgre"\n\n'
2021-03-27 18:43:33,811 (76857/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:43:33,811 (76857/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:43:35,913 (76857/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-03-27 18:43:37,529 (76947/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:43:37,529 (76947/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:43:40,305 (76947/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "user"\n\n'
2021-03-27 18:44:43,758 (78379/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-27 18:44:43,758 (78379/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-27 18:44:51,949 (78379/MainThread) pgcli.pgexecute ERROR - sql: 'exot', error: SyntaxError('syntax error at or near "exot"\nLINE 1: exot\n        ^\n')
2021-03-27 18:44:51,950 (78379/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "exot"\nLINE 1: exot\n        ^\n\n'
2021-03-29 03:06:44,875 (81080/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-29 03:06:44,875 (81080/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-29 03:09:23,583 (81080/MainThread) pgcli.pgexecute ERROR - sql: 'select * from building', error: UndefinedTable('relation "building" does not exist\nLINE 1: select * from building\n                      ^\n')
2021-03-29 03:09:23,583 (81080/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "building" does not exist\nLINE 1: select * from building\n                      ^\n\n'
2021-04-01 11:15:17,060 (81080/MainThread) pgcli.pgexecute ERROR - sql: 'exot', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2021-04-01 11:15:17,067 (81080/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-04-01 11:15:17,068 (81080/MainThread) pgcli.main ERROR - sql: 'exot', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2021-04-01 11:15:17,074 (81080/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 654, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 901, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2021-04-01 11:53:46,479 (47061/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-01 11:53:46,479 (47061/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-01 11:54:11,745 (47061/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"\n\n'
2021-04-01 11:54:13,259 (47767/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-01 11:54:13,259 (47767/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-03 19:28:11,719 (16281/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-03 19:28:11,719 (16281/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-03 19:28:15,351 (16281/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-04-03 19:28:24,202 (16569/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-03 19:28:24,202 (16569/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-03 20:13:53,989 (72433/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-03 20:13:53,989 (72433/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:17:33,825 (92744/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:17:33,825 (92744/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:18:28,671 (93901/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:18:28,671 (93901/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:18:44,525 (94245/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:18:44,525 (94245/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:21:03,066 (97289/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:21:03,066 (97289/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:21:16,450 (97582/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:21:16,450 (97582/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:21:51,254 (97582/MainThread) pgcli.pgexecute ERROR - sql: 'create database compeya-dev', error: SyntaxError('syntax error at or near "-"\nLINE 1: create database compeya-dev\n                               ^\n')
2021-04-10 02:21:51,255 (97582/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "-"\nLINE 1: create database compeya-dev\n                               ^\n\n'
2021-04-10 02:23:04,217 (99850/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:23:04,217 (99850/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:24:37,365 (2209/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:24:37,365 (2209/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:31:57,033 (11233/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:31:57,034 (11233/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-10 02:32:10,092 (11233/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"\n\n'
2021-04-10 02:32:11,700 (11534/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-10 02:32:11,701 (11534/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 00:14:38,166 (1090/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 00:14:38,166 (1090/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 00:14:41,626 (1090/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-04-11 00:15:11,756 (1843/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 00:15:11,756 (1843/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 00:15:13,177 (1843/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-04-11 00:15:17,395 (1965/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 00:15:17,395 (1965/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 00:15:19,345 (1965/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-04-11 00:19:22,803 (7115/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 00:19:22,803 (7115/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 00:19:27,704 (7115/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"\n\n'
2021-04-11 00:20:01,690 (7924/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 00:20:01,691 (7924/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 01:04:52,624 (64544/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 01:04:52,624 (64544/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 01:07:02,071 (67504/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 01:07:02,072 (67504/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-11 01:11:46,509 (73467/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-11 01:11:46,509 (73467/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-17 23:14:45,953 (2691/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-17 23:14:45,954 (2691/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-17 23:15:02,686 (2691/MainThread) pgcli.pgexecute ERROR - sql: '\\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\\n        ^\n')
2021-04-17 23:15:02,688 (2691/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\\n        ^\n\n'
2021-04-24 11:44:35,429 (33672/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-24 11:44:35,429 (33672/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-24 11:45:06,899 (33672/MainThread) pgcli.pgexecute ERROR - sql: 'show databases', error: UndefinedObject('unrecognized configuration parameter "databases"\n')
2021-04-24 11:45:06,900 (33672/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "databases"\n\n'
2021-04-24 11:45:09,243 (33672/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2021-04-24 11:45:09,244 (33672/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2021-04-24 11:45:26,804 (33672/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2021-04-24 11:45:26,805 (33672/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2021-04-25 08:05:28,715 (12438/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-25 08:05:28,731 (12438/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-25 08:05:28,738 (12438/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
2021-04-25 08:12:34,153 (12808/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-25 08:12:34,153 (12808/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-25 08:12:34,157 (12808/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
2021-05-01 10:22:27,615 (40147/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 10:22:27,615 (40147/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 10:22:29,319 (40147/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-01 10:22:48,784 (40216/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 10:22:48,784 (40216/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 10:53:38,256 (42446/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 10:53:38,256 (42446/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 11:18:00,226 (44384/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 11:18:00,226 (44384/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 11:18:01,708 (44384/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-01 11:45:04,580 (46308/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 11:45:04,581 (46308/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 11:45:27,312 (46308/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2021-05-01 11:45:27,313 (46308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2021-05-01 11:45:30,828 (46308/MainThread) pgcli.pgexecute ERROR - sql: 'show tabbles', error: UndefinedObject('unrecognized configuration parameter "tabbles"\n')
2021-05-01 11:45:30,828 (46308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tabbles"\n\n'
2021-05-01 11:45:33,858 (46308/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-05-01 11:45:33,859 (46308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-05-01 11:45:36,810 (46308/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2021-05-01 11:45:36,810 (46308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2021-05-01 13:07:02,144 (57504/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:07:02,144 (57504/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 13:07:15,227 (57504/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-01 13:09:09,400 (57679/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:09:09,400 (57679/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 13:09:22,675 (57679/MainThread) pgcli.pgexecute ERROR - sql: "insert into users (id, created_at, updated_at, email, last_name, first_name, permission)\nvalues\n('user-1', current_timestamp, current_timestamp, 'takanori.fukuyama@compeya.com', '福山', '貴徳', 'ADMIN')", error: UndefinedColumn('column "updated_at" of relation "users" does not exist\nLINE 1: insert into users (id, created_at, updated_at, email, last_n...\n                                           ^\n')
2021-05-01 13:09:22,676 (57679/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "updated_at" of relation "users" does not exist\nLINE 1: insert into users (id, created_at, updated_at, email, last_n...\n                                           ^\n\n'
2021-05-01 13:11:04,140 (57857/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:11:04,140 (57857/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 13:21:07,458 (59071/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:21:07,458 (59071/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 13:21:27,370 (59071/MainThread) pgcli.pgexecute ERROR - sql: 'exot', error: SyntaxError('syntax error at or near "exot"\nLINE 1: exot\n        ^\n')
2021-05-01 13:21:27,372 (59071/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "exot"\nLINE 1: exot\n        ^\n\n'
2021-05-01 13:29:09,285 (59786/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:29:09,285 (59786/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 13:37:30,785 (60790/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 13:37:30,786 (60790/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 17:49:31,965 (88484/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 17:49:31,966 (88484/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-01 18:03:47,622 (88484/MainThread) pgcli.pgexecute ERROR - sql: 'insert into property_characters (id, created_at, updated_at, strage_for_shoes)\n  values\n  (1, current_timestamp, current_timestamp, true)', error: UniqueViolation('duplicate key value violates unique constraint "property_characters_pkey"\nDETAIL:  Key (id)=(1) already exists.\n')
2021-05-01 18:03:47,627 (88484/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "property_characters_pkey"\nDETAIL:  Key (id)=(1) already exists.\n\n'
2021-05-01 18:04:35,278 (88484/MainThread) pgcli.pgexecute ERROR - sql: 'insert into properties (id, created_at, updated_at, published, building_id, characters_id, rent, management_fee, deposit, gratuity_fee, brokerage_fee, free_rent)\n  values\n  (4, current_timestamp, current_timestamp, true, 1, 2, 60000, 3000, 0, 0, 0, false),', error: SyntaxError('syntax error at end of input\nLINE 3: ...current_timestamp, true, 1, 2, 60000, 3000, 0, 0, 0, false),\n                                                                       ^\n')
2021-05-01 18:04:35,279 (88484/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 3: ...current_timestamp, true, 1, 2, 60000, 3000, 0, 0, 0, false),\n                                                                       ^\n\n'
2021-05-01 18:55:22,941 (97351/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-01 18:55:22,941 (97351/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-08 15:08:31,690 (13942/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-08 15:08:31,690 (13942/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-08 15:08:33,189 (13942/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-08 15:08:48,597 (13988/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-08 15:08:48,597 (13988/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-08 22:19:40,873 (13988/MainThread) pgcli.pgexecute ERROR - sql: "insert into oauth_informations (email, user_id, provider_uid, created_at, updated_at) values ('takanori.fukuyama@compeya.com', 'user-1', 'google-uid-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)", error: NotNullViolation('null value in column "organization_id" of relation "oauth_informations" violates not-null constraint\nDETAIL:  Failing row contains (1, 2021-05-08 13:19:42.964747+00, 2021-05-08 13:19:42.964747+00, takanori.fukuyama@compeya.com, user-1, google-uid-1, GOOGLE, null).\n')
2021-05-08 22:19:40,877 (13988/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.NotNullViolation: null value in column "organization_id" of relation "oauth_informations" violates not-null constraint\nDETAIL:  Failing row contains (1, 2021-05-08 13:19:42.964747+00, 2021-05-08 13:19:42.964747+00, takanori.fukuyama@compeya.com, user-1, google-uid-1, GOOGLE, null).\n\n'
2021-05-08 22:21:20,756 (13988/MainThread) pgcli.pgexecute ERROR - sql: "insert into oauth_informations (email, user_id, provider_uid, created_at, updated_at, organization_id) values ('takanori.fukuyama@compeya.com', 'user-1', 'google-uid-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,1)", error: ForeignKeyViolation('insert or update on table "oauth_informations" violates foreign key constraint "fk_oauth_informations_organizations"\nDETAIL:  Key (organization_id)=(1) is not present in table "organizations".\n')
2021-05-08 22:21:20,771 (13988/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.ForeignKeyViolation: insert or update on table "oauth_informations" violates foreign key constraint "fk_oauth_informations_organizations"\nDETAIL:  Key (organization_id)=(1) is not present in table "organizations".\n\n'
2021-05-08 22:22:14,922 (13988/MainThread) pgcli.pgexecute ERROR - sql: "insert into oauth_informations (email, user_id, provider_uid, created_at, updated_at, organization_id) values ('takanori.fukuyama@compeya.com', 'user-1', 'google-uid-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,1)", error: ForeignKeyViolation('insert or update on table "oauth_informations" violates foreign key constraint "fk_oauth_informations_organizations"\nDETAIL:  Key (organization_id)=(1) is not present in table "organizations".\n')
2021-05-08 22:22:14,923 (13988/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.ForeignKeyViolation: insert or update on table "oauth_informations" violates foreign key constraint "fk_oauth_informations_organizations"\nDETAIL:  Key (organization_id)=(1) is not present in table "organizations".\n\n'
2021-05-08 22:22:30,040 (13988/MainThread) pgcli.pgexecute ERROR - sql: "insert into oauth_informations (email, user_id, provider_uid, created_at, updated_at) values ('takanori.fukuyama@compeya.com', 'user-1', 'google-uid-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)", error: NotNullViolation('null value in column "organization_id" of relation "oauth_informations" violates not-null constraint\nDETAIL:  Failing row contains (2, 2021-05-08 13:22:32.128702+00, 2021-05-08 13:22:32.128702+00, takanori.fukuyama@compeya.com, user-1, google-uid-1, GOOGLE, null).\n')
2021-05-08 22:22:30,040 (13988/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.NotNullViolation: null value in column "organization_id" of relation "oauth_informations" violates not-null constraint\nDETAIL:  Failing row contains (2, 2021-05-08 13:22:32.128702+00, 2021-05-08 13:22:32.128702+00, takanori.fukuyama@compeya.com, user-1, google-uid-1, GOOGLE, null).\n\n'
2021-05-09 16:59:19,962 (41907/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-09 16:59:19,963 (41907/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-09 16:59:20,634 (41907/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-09 16:59:37,610 (41979/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-09 16:59:37,610 (41979/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-09 16:59:43,258 (41979/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-05-09 17:00:02,766 (42071/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-09 17:00:02,766 (42071/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-12 09:21:40,934 (93069/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-12 09:21:40,934 (93069/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-13 19:10:38,738 (93069/MainThread) pgcli.pgexecute ERROR - sql: 'select * from buildings where id is 45', error: SyntaxError('syntax error at or near "45"\nLINE 1: select * from buildings where id is 45\n                                            ^\n')
2021-05-13 19:10:38,744 (93069/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "45"\nLINE 1: select * from buildings where id is 45\n                                            ^\n\n'
2021-05-15 19:07:20,224 (57963/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-05-15 19:07:20,225 (57963/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-05-15 19:07:32,118 (57963/MainThread) pgcli.pgexecute ERROR - sql: 'show tabke', error: UndefinedObject('unrecognized configuration parameter "tabke"\n')
2021-05-15 19:07:32,119 (57963/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tabke"\n\n'
2021-05-15 19:14:39,877 (57963/MainThread) pgcli.pgexecute ERROR - sql: 'select * from pg_timezone_names where "abbrev" = JST', error: UndefinedColumn('column "jst" does not exist\nLINE 1: select * from pg_timezone_names where "abbrev" = JST\n                                                         ^\n')
2021-05-15 19:14:39,879 (57963/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "jst" does not exist\nLINE 1: select * from pg_timezone_names where "abbrev" = JST\n                                                         ^\n\n'
2021-05-15 19:14:47,180 (57963/MainThread) pgcli.pgexecute ERROR - sql: 'select * from pg_timezone_names where "abbrev" = "JST"', error: UndefinedColumn('column "JST" does not exist\nLINE 1: select * from pg_timezone_names where "abbrev" = "JST"\n                                                         ^\n')
2021-05-15 19:14:47,180 (57963/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "JST" does not exist\nLINE 1: select * from pg_timezone_names where "abbrev" = "JST"\n                                                         ^\n\n'
